/**
 * Represents an HTML tag, together with the content.
 * @constructor
 * @param {String} tagname - The name of the tag.
 * @param {String} id - The id of the tag.
 * @param {Array} classes - Array containing the classes of the tag.
 * @param {Object} attributes - Object containing the attributes and values
 * of this tag.
 * @param {Array|undefined} content - The contents of this tag.
 * @private
 */
var Tag = function Tag(tagname, id, classes, attributes, content) {
	this.tagname = tagname;
	this.attributes = (attributes === undefined ? {} : attributes);
	this.id = (id === undefined ? false : id);
	this.classes = (classes === undefined ? [] : classes);
	this.content = (content === undefined ? [] : content);
};

/**
 * Represents a segment that is dynamically updated.
 * @constructor
 * @param {String} variablename - The name of the variable, that should be
 * used to dynamically update this segment.
 * @public
 */
var DynamicSegment = function DynamicSegment(expression) {
	this.expression = expression;
};

/**
 * Represents a single Sora definition.
 * @constructor
 * @param {String} type The type of the Sora
 * @param {String} name The name of the attribute, if the type is attribute.
 * @param {String} value The value of the Sora.
 * @private
 */
var Sora = function Sora(type, name, value) {
	this.type = type;
	this.name = name;
	this.value = value;
};

/**
 * Object with options, and metadata of a conversion.
 * @constructor
 * @param {Array} js Array of JavaScript codes that are also generated by the
 * converter.
 * @param {Array} crumbs Object containing all the crumbs.
 * @param {Object} options Object containing all the options, for possible
 * values and default values, see redstone-parser.js.
 */
var ConverterContext = function ConverterContext(js, crumbs, options) {
	this.js = js;
	this.crumbs = crumbs;
	this.options = options;
}

exports.Tag = Tag;
exports.DynamicSegment = DynamicSegment;
exports.Sora = Sora;
exports.ConverterContext = ConverterContext;